### PR TITLE
LU-455 Fix applied to 2.0.65-llnl

### PR DESCRIPTION
**Pull request by prakashsurya**
Hey Chris,

I made the change we talked about with Brian. It passed the 'made dist' check that I ran on zwicky so I pushed it up to whamcloud's gerritt.

Here is that patch applied to our 2.0.65-llnl tree. Although, unfortunately, it did not apply cleanly. I had to manually resolve a small conflict with the top level autoMakefile.am when cherry picking the patch I pushed to gerritt. Let me know if you have any issues with this pull request.

Prakash

### CODE REVIEW

**Comment by nedbass** [comment]
Does this address the issue with Module.symvers not getting the ldiskfs symbols?

**Comment by prakashsurya** [comment]
Ahh.. I forgot about that. No it does not.

I saw that patch you proposed Ned. Is that accepted as the "right" fix? If so I can pull that in.

**Comment by nedbass** [comment]
I think the patch I proposed may break builds with ldiskfs disabled (i.e. client-only builds) since in that case the Module.symver target won't exist.  We probably need to duplicate what was done with EXTRA_SOURCES before, only with a better-chosen variable name.

**Comment by prakashsurya** [comment]
Why was that code with EXTRA_SOURCES taken out in the first place? From the
commit message is states "the incorrect EXTRA_SOURCES instance was removed",
but why was it incorrect? Because Module.symvers isn't really a source file?

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 02:31:59PM -0700, Prakash-Surya wrote:

> Why was that code with EXTRA_SOURCES taken out in the first place? From the
> commit message is states "the incorrect EXTRA_SOURCES instance was removed",
> but why was it incorrect? Because Module.symvers isn't really a source file?

Variables ending in _SOURCES have a special signifigance to automake.  See

http://www.gnu.org/s/hello/manual/automake/Default-_005fSOURCES.html

**Comment by prakashsurya** [comment]
Hmm.. I feel like that file should have all of the kernel modules as
dependencies. That would force it to get regenerated whenever a module was
modified, right?

**Comment by morrone** [comment]
Point me to Ned's patch?

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 04:03:41PM -0700, morrone wrote:

> Point me to Ned's patch?

It was just a comment in the bugzilla:

https://chaos.llnl.gov/bugzilla/show_bug.cgi?id=1213#c1

Though I am currently proposing we do something like this:

diff --git a/autoMakefile.am b/autoMakefile.am
index cf1114a..0257cb9 100644
--- a/autoMakefile.am
+++ b/autoMakefile.am
@@ -18,6 +18,7 @@ if LDISKFS_ENABLED
 if !LDISKFS_IN_KERNEL

 EXTRA_DIST += @SYMVERFILE@
+ALL_SOURCES_DEPS := @SYMVERFILE@

 @SYMVERFILE@:
        touch @SYMVERFILE@
diff --git a/build/autoMakefile.am.toplevel b/build/autoMakefile.am.toplevel
index 8b72d47..2c083de 100644
--- a/build/autoMakefile.am.toplevel
+++ b/build/autoMakefile.am.toplevel
@@ -50,7 +50,7 @@ doxygen-%: build/doxyfile.%
 if MODULES
 sources: all-sources

-all-sources: $(EXTRA_SOURCES)
+all-sources: $(ALL_SOURCES_DEPS)
        for dir in $(SOURCES_SUBDIRS) ; do \
                $(MAKE) sources -C $$dir || exit $$? ; \
        done

**Comment by morrone** [comment]
The failure I currently see for 2.0.65-llnl is this:

DEBUG: make: **\* No rule to make target `/usr/src/lustre-ldiskfs-3.1.4/2.6.32-131.6.1.2chaos.ch5.x86_64/Module.symvers', needed by`Module.symvers'.  Stop.
DEBUG: RPM build errors:

Are you trying to solve some other problem?  The connection isn't obvious to me.

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 03:26:13PM -0700, Prakash-Surya wrote:

> Hmm.. I feel like that file should have all of the kernel modules as
> dependencies. That would force it to get regenerated whenever a module was
> modified, right?

No, the dependency works the other way. For a rule

foo: bar
    # do stuff

the bar target must be up-to-date before foo is executed.  

In our case, the Module.symvers make target only exists to populate
Module.symvers with information on external symbols (i.e. from ldisfs or zfs)
that the lustre modules depend on. It has nothing to do with adding symbol
information for the lustre modules themselves.  I believe that is handled by
the kernel build system as the lustre modules are built.

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 04:15:29PM -0700, morrone wrote:

> The failure I currently see for 2.0.65-llnl is this:
> 
> DEBUG: make: **\* No rule to make target `/usr/src/lustre-ldiskfs-3.1.4/2.6.32-131.6.1.2chaos.ch5.x86_64/Module.symvers', needed by`Module.symvers'.  Stop.
> DEBUG: RPM build errors:
> 
> Are you trying to solve some other problem?  The connection isn't obvious to me.

I wasn't in on the original discussion that prompted this pull request.  But I
made an inline comment about the above error.  I don't think the ldiskfs
symvers file should be a dependency for the Module.symvers make target.

I only brought up the EXTRA_SOURCES issue (LLNL bz 1213) because if we're
updating Brian's original gerrit submission we should fix that too.

Ned

**Comment by prakashsurya** [comment]
I tried sending this out earlier through email, but it doesn't look like it made it to this thread. Im not quite sure why it didn't make it?

Anyways...

Looking at the kernel docs (Documentation/kbuild/modules.txt), I stumbled upon
this:

```
    Use make variable KBUILD_EXTRA_SYMBOLS in the Makefile
            If it is impractical to copy Module.symvers from another
            module, you can assign a space separated list of files to
            KBUILD_EXTRA_SYMBOLS in your Makfile. These files will be
            loaded by modpost during the initialisation of its symbol
            tables.
```

I then tested using this variable with the following patch, and it seemed to
work:

```
    diff --git a/Makefile.in b/Makefile.in
    index 9272de6..7acd518 100644
    --- a/Makefile.in
    +++ b/Makefile.in
    @@ -1,4 +1,6 @@
     subdir-m += @LIBCFS_SUBDIR@ lnet
     subdir-m += lustre

    +KBUILD_EXTRA_SYMBOLS=@LDISKFS_DIR@/ldiskfs/@SYMVERFILE@
    +
     @INCLUDE_RULES@
```

Of course this patch can't be used as is, but it serves as a good proof of
concept. I think this might be the simplest solution, and it certainly feels
like the "right" solution to me.

What do you think?

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 04:55:52PM -0700, Prakash-Surya wrote:

> ```
>     +KBUILD_EXTRA_SYMBOLS=@LDISKFS_DIR@/ldiskfs/@SYMVERFILE@
>     +
>      @INCLUDE_RULES@
> ```
> 
> Of course this patch can't be used as is, but it serves as a good proof of
> concept. I think this might be the simplest solution, and it certainly feels
> like the "right" solution to me.
> 
> What do you think?

That is definitely cleaner than the current method.

**Comment by morrone** [comment]
Well, that scares me a bit.  I think I want to leave that to a separate patch and just fix it the quick-and-dirty way for now.

I am concerned that may have allowed you to build on OUR system with an external ldiskfs, but does it really work for building ldiskfs in-tree?

**Comment by nedbass** [comment]
On Fri, Jul 22, 2011 at 05:14:28PM -0700, morrone wrote:

> Well, that scares me a bit.  I think I want to leave that to a separate patch and just fix it the quick-and-dirty way for now.
> 
> I am concerned that may have allowed you to build on OUR system with an external ldiskfs, but does it really work for building ldiskfs in-tree?

You would still need the if-else logic under the @SYMVERFILE@ rule in
autoMakefile.am to get the right path, but you could eliminate the use of touch
grep and cat by setting KBUILD_EXTRA_SYMBOLS instead.  But yeah, that should
probably be a separate patch.

**Comment by morrone** [comment]
Ok, I made one final change.  It is in our 2.0.65-2chaos, and I pushed it to whamcloud.

But like I said, we can pursue the KBUILD_EXTRA_SYMBOLS method in another patch.

**Comment by prakashsurya** [comment]
Sounds good. We can continue the KBUILD_EXTRA_SYMBOLS discussion in the bugzilla bug: https://chaos.llnl.gov/bugzilla/show_bug.cgi?id=1213

**Pull request closed without merging**
