### PR TITLE
b=1282 Update /etc/init.d/lnet for Lustre 2.1

### PR DESCRIPTION
**Pull request by prakashsurya**
The /etc/init.d/lnet script needed to be updated to reflect the set of
modules that are used in Lustre 2.1.

Signed-off-by: Prakash Surya surya1@llnl.gov
Change-Id: If6e2b249de5e47732abdb62ee062cb0f369185e2

### CODE REVIEW

**Comment by prakashsurya** [comment]
This change allows me to use 'lnet stop' to successfully unload the modules in the small testing I did in my VM.

I _think_ a few of the listed modules can be removed as well. Such as llite, obdfilter, kqswlnd, etc.. Although I wanted to ask before I took those out.

**Comment by morrone** [comment]
obdfilter is still part of lustre 2.1.  If llite not longer is, it can be removed.  The lnds are conditionally compiled based if you have support for that hardware.  If the code to build it still exists in 2.1, then it stays in.  If not, it comes out.

**Comment by prakashsurya** [comment]
I tried 'lnet stop' without reordering osc and ost but it wouldn't work in my testing. It was showing lov was dependent on osc, and obdfilter dependent on ost, which is why I moved them.

**Comment by prakashsurya** [comment]
And I'm not sure if llite and the lnd modules are still in 2.1, I just didn't see them being used in my testing. Although, that could just mean they are aren't used in _our_ configuration, but still need to be in there.

**Comment by morrone** [comment]
Ok, I'll buy it.

**Pull request merged**
